"use strict";

const STATES = {
  START: "START",
  OPERATION: "OPERATION",
  END: "END",
};

const EXPIRY_TIME_1 = 1000 * 10;
const EXPIRY_TIME_2 = 1000 * 20;
// const QUEUE_ACTION_LATENCY_OFFSET_MARGIN = 0;
// const QUEUE_ACTION_LATENCY_OFFSET_MARGIN = 150;
const QUEUE_ACTION_LATENCY_OFFSET_MARGIN = 200;
const MINIMUM_QUEUE_ACTION_TIME = 100;

const TIMES = {
  EXPIRY_TIME_1,
  EXPIRY_TIME_2,
  QUEUE_ACTION_LATENCY_OFFSET_MARGIN,
  MINIMUM_QUEUE_ACTION_TIME,
};

module.exports = {
  constants: {
    STATES,
    TIMES,
  },
};
